name: Release
on:
  push:
    release:
      types: [created]      

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          cache: yarn

      - run: yarn install

      - run: yarn run build      
      - run: npm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.GH_PACKAGE_TOKEN }}
      
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
